### PR TITLE
MPRIS management update

### PR DESCRIPTION
**Pull request by keops-dev**
As Deezer uses an old version of Chromium, [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) is not properly supported. In particular, album covers are not displayed. You might want to keep deezer-linux as close to the windows version as possible, but just in case, I'm sharing my work.

The result on my Debian (Gnome 43.9)
image

### CODE REVIEW

**Comment by Meincrakker** [comment]
Hi, great you got this to work. I compiled this myself and everything seems to work fine. Except I just noticed that if you click on the notifications icon next to the profile and then on any link the app closes its main window and shows this error message, preventing me from playing any music.  Is this a new bug on my end or somehow connected to this edit?
image

**Comment by anatolethien** [comment]
Can't wait for this update!!

**Comment by keops-dev** [comment]
@Meincrakker I didn't notice this on my side, but I only compiled in .deb. Maybe you built an AppImage or something else?

**Comment by Meincrakker** [comment]
@keops-dev Good suggestion, the Appimage seems to work great. Using the rpm build seems to create this error pretty reproducible.

**Comment by aunetx** [comment]
Hello, thank you very much for your work, this is amazing! The issue @Meincrakker raised seems a bit weird, but I can't reproduce it right now... I think merging it first, and then looking at what is wrong is the best strategy (especially since this bug is a bit secondary if that's the only way to reproduce it!)

**Comment by andrevmatos** [comment]
Hello. This doesn't seem to be working well on latest version (KDE Wayland, NixOS unstable).
No cover art in MPRIS, nor progress slider.

**Pull request merged**
